name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

env:
  PROJECT: vagemcast.xcodeproj
  SCHEME: vagemcast

jobs:
  unitTests:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests
        run: xcodebuild clean build test -project ${{ env.PROJECT }} -scheme ${{ env.SCHEME }} -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" | xcpretty
        working-directory: ./Apps
        